app_calculadora/urls.py
from django.urls import path
from app_calculadora import views

urlpatterns = [
    path('', views.calculadora_view, name='calculadora')
]

app_dashboard/urls.py
from django.urls import path
from app_dashboard import views


urlpatterns = [
    path('', views.home_view, name='home')
]

app_listaDeTarefas/urls.py
from django.urls import path
from app_listaDeTarefas import views

app_name = 'ListaDeTarefa'

urlpatterns = [
    path('', views.lista_tarefa_view, name='lista_tarefas'),
    path('delete/<tarefa_id>', views.delete_tarefa, name='delete_tarefa'),
    path('editar/<tarefa_id>', views.editar_tarefa, name='editar_lista'),
]

django_js/django_js/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_dashboard.urls')),
    path('lista_de_tarefas/', include('app_listaDeTarefas.urls')),
    path('calculadora/', include('app_calculadora.urls')),
]

app_calculadora/models.py
from django.db import models

# Create your models here.

app_listaDeTarefas/models.py
from django.db import models

STATUS = [
    ('fazer', 'A fazer'),
    ('concluido', 'Concluido')
]

class ListadeTareda(models.Model):
    tarefa = models.CharField(max_length=255, verbose_name='Tarefa')
    status = models.CharField(max_length=30, choices=STATUS, default='fazer')

    def __str__(self):
        return self.tarefa

app_calculadora/views.py
from django.shortcuts import render

def calculadora_view(request):
    return render(request, 'pages/home_calculadora.html', context={
        'calculadora': calculadora_view,
    })

app_dashboard/views.py
from django.shortcuts import render

def home_view(request):
    return render(request, 'pages/home.html', context={
        'home': home_view,
    })

app_listaDeTarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app_listaDeTarefas.models import ListadeTareda
from app_listaDeTarefas.form import ListadeTarefaForm, EditListadeTarefaForm

def lista_tarefa_view(request):
    if request.method == 'POST':
        form = ListadeTarefaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ListaDeTarefa:lista_tarefas')
    else:
        form = ListadeTarefaForm()
    
    tarefas = ListadeTareda.objects.all()
    return render(request, 'pages/home_lista.html', context={
        'lista_tarefa': lista_tarefa_view,
        'form': form,
        'tarefas': tarefas
    })

def delete_tarefa(request, tarefa_id):
    tarefa = get_object_or_404(ListadeTareda, pk=tarefa_id)
    
    if request.method == 'POST':
        tarefa.delete()
        tarefas = ListadeTareda.objects.all()
        return redirect('ListaDeTarefa:lista_tarefas')

    return render(request, 'pages/home_lista.html', context={
        'lista_tarefa': lista_tarefa_view,
        'tarefas': tarefas
    })

def editar_tarefa(request, tarefa_id):
    tarefa = get_object_or_404(ListadeTareda, pk=tarefa_id)
    if request.method == 'POST':
        form = EditListadeTarefaForm(request.POST, instance=tarefa)
        if form.is_valid():
            form.save()
            return redirect('ListaDeTarefa:lista_tarefas')
        else:
            form = EditListadeTarefaForm(instance=tarefa)
        
        return render(request, "ListaDeTarefa:editar_lista", context={
            'form': form,
        })

app_calculadora/templates/pages/home_calculadora.html
{% extends "global/index.html" %}
{% load static %}


{% block container %}
<h1>oi</h1>

{% endblock container %}

app_dashboard/templates/pages/home.html
{% extends "global/index.html" %}
{% load static %}

{% block container %}

<h1>oi</h1>

{% endblock container %}

app_listaDeTarefas/templates/pages/editar_lista.html
{% extends "global/index.html" %}
{% load static %}



{% block container %}
{% load compress %}
{% compress css %}
<link rel="stylesheet" href="/static/listaTarefa/css_lista_de_tarefas/style.css" type="text/css" charset="utf-8">
{% endcompress %}
<script defer src="{% static "listaTarefa/js/main_tarefa.js" %}"></script>
<h1 class>Lista de tarefas</h1>
<div class="table-responsive" style="text-align: left">
  <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Tarefa</th>
          <th scope="col">Status</th>
          <th scope="col">Editar</th>
          <th scope="col">Apagar</th>
          <th scope="col">Salvar</th>
        </tr>
      </thead>
      {% for tarefa in tarefas %}
        <tbody>
          <tr>
            <td><p style="font-size: 1.3rem;">{{tarefa.tarefa}}</p></td>
            <td>
              <p style="font-size: 1.3rem;">{{ tarefa.get_status_display }}</p>
            </td>
            <td>
              <button>SALVAR</button>
            </td>
          </tr>
        </tbody>
      {% endfor %}
  </table>  
</div>

{% endblock container %}

app_listaDeTarefas/templates/pages/home_lista.html
{% extends "global/index.html" %}
{% load static %}



{% block container %}
{% load compress %}
{% compress css %}
<link rel="stylesheet" href="/static/listaTarefa/css_lista_de_tarefas/style.css" type="text/css" charset="utf-8">
{% endcompress %}
<script defer src="{% static "listaTarefa/js/main_tarefa.js" %}"></script>
<h1 class>Lista de tarefas</h1>
<form method="POST">
  {% csrf_token %}    
  {% for fields in form %}
    <div class="form-group">
      {{ form.tarefa }}
      <button id="btn-tarefa" class="btn btn-primary">Adicionar</button>
    </div>
  {% endfor %}   
</form>
<div style="text-align: left">
  <table class="table">
      <thead>
        <tr>
          <th scope="col">Tarefa</th>
          <th scope="col">Status</th>
          <th scope="col">APAGAR</th>
        </tr>
      </thead>
      {% for tarefa in tarefas %}
        <tbody>
            <tr>
              <td><p style="font-size: 1.3rem;">{{tarefa.tarefa}}</p></td>
              <td>
                <select name="status" id="id_status">
                  <option value="fazer">A fazer</option>
                  <option value="concluido">Concluido</option>
                </select>
              </td>
              <td>
                <form action="{% url "ListaDeTarefa:delete_tarefa" tarefa.id %}" method="post">
                  {% csrf_token %}
                  <input type="submit" value="X" style="height: auto; left: auto;">
                </form>
              </td>
            </tr>
        </tbody>
      {% endfor %}
  </table>  
</div>

{% endblock container %}